name: Deploy to Azure Web App - Otto Portfolio Optimizer

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch
  pull_request:
    branches:
      - main  # Trigger deployment on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Set up Docker Buildx (for multi-platform support)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image to Docker Hub
    - name: Build and Push Docker image
      run: |
        docker build -t calvaro/mdm-portfolio-optimizer:latest .
        docker push calvaro/mdm-portfolio-optimizer:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the build job is finished before deploying

    steps:
    # Checkout the code from the repository again
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Azure Web App Deployment
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Otto-Portfolio-Optimizer'  # Azure App name
        slot-name: 'production'  # or use another slot if needed
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Secret with the Azure publish profile
        package: '.'  # Pointing to the root of your repo (where the Dockerfile is)
        images: 'calvaro/mdm-portfolio-optimizer:latest'

    # Output the status
    - name: Azure Deployment Logs
      run: |
        echo "Deployment logs and info from Azure:"
        echo "App URL: https://otto-portfolio-optimizer.azurewebsites.net"
